### ISSUE TITLE
Browserify support

### ISSUE THREAD

**Issue by flip111** [thingdom/node-neo4j#182]
I tried the new v2 branch as browserify standalone package so i can quickly prototype some client side app without having to setup a server (other than the database itself). Using the following commands, which didn't work. I don't have enough expertise with the node ecosystem to tell what's the actual problem here is in the first place.

```
D:\dev\http\test>npm install neo4j@2.0.0-RC2
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine boom@2.9.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
neo4j@2.0.0-RC2 node_modules\neo4j
├── underscore@1.7.0
└── request@2.65.0 (forever-agent@0.6.1, aws-sign2@0.6.0, caseless@0.11.0, stringstream@0.0.4, oauth-sign@0.8.0, tunnel-
agent@0.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.3, qs@5.2.0, combined-stream@1.0.5,
form-data@1.0.0-rc3, tough-cookie@2.2.0, mime-types@2.1.7, http-signature@0.11.0, bl@1.0.0, hawk@3.1.0, har-validator@2.
0.2)

D:\dev\http\test>browserify ./node_modules/neo4j -s neo4j > neo4j.js
Error: Cannot find module './C:/Users/flip111/AppData/Roaming/npm/node_modules/browserify/node_modules/insert-module-gl
obals/node_modules/is-buffer/index.js' from 'D:\dev\http\test\node_modules\neo4j\node_modules\request\node_modules\co
mbined-stream\lib'
    at C:\Users\flip111\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\flip111\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\flip111\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\flip111\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by aseemk** [comment]
Sorry for forgetting to ever respond to this, @flip111!

I'm not knowledgeable with Browserify much. Did you figure this out? Or does anyone else know?

**Comment by flip111** [comment]
The problem resolved itself somehow.
