### ISSUE TITLE
Cannot create new node.

### ISSUE THREAD

**Issue by whitef0x0** [thingdom/node-neo4j#209]
When creating a new node with node-neo4j I get this error.

 ```
Error saving new node to database: TypeError: (e.message || "").split is not a function
    at formatStack (/Users/admin/Documents/helpbase/node_modules/neo4j/lib/Node.js:2:7311)
    at Error.stack (/Users/admin/Documents/helpbase/node_modules/neo4j/lib/Node.js:2:8372)
    at formatError (util.js:631:15)
    at formatValue (util.js:536:18)
    at inspect (util.js:198:10)
    at exports.format (util.js:133:20)
    at Console.warn (console.js:51:37)
    at repl:3:9
    at __$Node_prototype_save__1 (/Users/admin/Documents/helpbase/node_modules/neo4j/lib/Node.js:101:24)
    at /Users/admin/Documents/helpbase/node_modules/neo4j/lib/Node.js:2:62
```

I'm using node v6.3.0, node-neo4j v1.1.1 on Mac OSX v10.11.3 with Neo4J v3.0.4

**Comment by whitef0x0** [comment]
nvm. Had the wrong version of neo4j installed
